### ISSUE TITLE
Try to access list of worker nodes ips

### ISSUE THREAD

**Issue by StanvanHoorn** [JWDobken/terraform-hcloud-kubernetes#19]
Hi,

I tried to access the list of worker nodes to add them automatically to a hcloud loadbalancer.

Can you provide me with information on how to do that with your module?

Thanks :)

I trying to achieve something like this:
```
resource "hcloud_load_balancer_target" "load_balancer_target" {
  for_each = toset(module.hcloud_kubernetes_cluster.worker_nodes)

  type = "server"
  load_balancer_id = hcloud_load_balancer.load_balancer.id
  hcloud_load_balancer_target  = each.value.id
}
```

**Comment by JWDobken** [comment]
Hi Stan,

Thank you for your input!
With the 0.1.8 release, the worker nodes from the output `module.hcloud_kubernetes_cluster.worker_nodes` are the actual worker node objects, which is much more logical!

In addition to this, you can use the [output](https://github.com/JWDobken/terraform-hcloud-kubernetes/blob/00205bbb75acd0728f237c4577f853007c920e7e/outputs.tf#L37) `module.hcloud_kubernetes_cluster.worker_nodes_ids`
