### ISSUE TITLE
Could you please add examples manifest of publishing via ingress

### ISSUE THREAD

**Issue by rrrru** [JWDobken/terraform-hcloud-kubernetes#28]

**Comment by JWDobken** [comment]
Hi @rrrru,

The README includes an explanation how to deploy the nginx-ingress controller with a load balance: https://github.com/JWDobken/terraform-hcloud-kubernetes#load-balancer

Publishing with the ingress-controller is beyond the scope of this repo, [you can learn more about Ingress on the main Kubernetes documentation site](https://kubernetes.io/docs/concepts/services-networking/ingress/).

**Comment by rrrru** [comment]
@JWDobken Thanks for the answer and sorry for the dumb question
