### ISSUE TITLE
Error: file provisioner error

### ISSUE THREAD

**Issue by mashkovd** [JWDobken/terraform-hcloud-kubernetes#40]
I create file **values.tfvars**

```
cluster_name = "my_cluster"
hcloud_token = "hcloud_token"
hcloud_ssh_keys = ["ssh_key_name"]
worker_count = 1
```

and after i run command 
terraform apply -var-file values.tfvars 

manually i add  **private_key**
Enter a value:  file("/home/USER/.ssh/private_key")

after that i see 

```
module.cluster.hcloud_server.control_plane_node[0]: Provisioning with 'file'...
╷
│ Error: file provisioner error

Failed to read ssh private key: no key found
```

Pls, write how i can properly set value for **private_key**

**Comment by mashkovd** [comment]
i use follow command 
`terraform apply -var-file values.tfvars -var="private_key=$(cat ~/.ssh/hcloud)"`
and it does work

how properly add **private_key** to values.tfvars

**Comment by JWDobken** [comment]
I am aware of the issue and will fix it when I find some time.

In the meantime you can resolve the issue by tighdown to the latest release:

```tf
module "hcloud_kubernetes_cluster" {
  source                    = "JWDobken/kubernetes/hcloud"
  version                   = "v0.3.1"
  ...
```

I'll keep this issue open until problem is fixed

**Comment by rodriguesl3** [comment]
I got the same error, to make it works I added the ssh to agent;
```
eval $(ssh-agent -s)
ssh-add /path/to/<your-key>
```
